print("Cangkok adalah cara memperbanyak tanaman")
print("Dengan menumbuhkan akar pada batang yang masih menempel pada tanaman induk")
print("Cara Kerja Cangkok")
print("1. Pilih batang yang sehat dan cukup tua")
print("2. Kupas kulit batang secara melingkar.")
print("3. Bersihkan bagian kambium yang telah dikupas.")
print("4. Bungkus sayatan dengan media tanam yang lembab")
print("5. Bungkus dengan plastik atau sabut kelapa, lalu ikat kedua ujungnya.")
print("6. Siram atau jaga media agar tetap lembap.")
print("7. Setelah akar tumbuh, potong batang di bawah bagian yang dicangkok.")
print("8. Tanam batang tersebut ke dalam pot atau tanah.")